interface Rewards{
  base:number;
  levelBonus:number;
  experience:number;
  energy:number;
}

interface FaucetSetting{
  level:number;
  requiredClicks:number;
  vipCost:number;
  rewards:Rewards;
}

interface VipDiscount{
  monthCount:number;
  discount:number;
}

export const getSettings = (level:number)=>{
  return handfaucetSettings.filter(set=>set.level===level)[0];
}

export const getVipDiscount = (monthCount:number):number | null =>{
  const filterResult = DiscountOnVIP.filter(dis=>dis.monthCount === monthCount);
  if(filterResult.length){
    const item = filterResult[0];
    return item.discount;
  }
  return null;
}

export const handfaucetSettings:FaucetSetting[] = [
  {
    level:1,
    requiredClicks:0,
    vipCost:1000,
    rewards:{
      base:10,
      levelBonus:0,
      experience:10,
      energy:10,
    }
  },
  {
    level:2,
    requiredClicks:1,
    vipCost:10000,
    rewards:{
      base:10,
      levelBonus:10,
      experience:10,
      energy:10,
    }
  },
  {
    level:3,
    requiredClicks:10,
    vipCost:50000,
    rewards:{
      base:20,
      levelBonus:20,
      experience:12,
      energy:11,
    }
  },
  {
    level:4,
    requiredClicks:100,
    vipCost:100000,
    rewards:{
      base:50,
      levelBonus:30,
      experience:15,
      energy:12,
    }
  },
  {
    level:5,
    requiredClicks:1000,
    vipCost:500000,
    rewards:{
      base:100,
      levelBonus:40,
      experience:20,
      energy:13,
    }
  },
  {
    level:6,
    requiredClicks:10000,
    vipCost:1000000,
    rewards:{
      base:500,
      levelBonus:50,
      experience:25,
      energy:14,
    }
  },
  {
    level:7,
    requiredClicks:100000,
    vipCost:5000000,
    rewards:{
      base:5000,
      levelBonus:60,
      experience:32,
      energy:15,
    }
  },
  {
    level:8,
    requiredClicks:1000000,
    vipCost:10000000,
    rewards:{
      base:100000,
      levelBonus:70,
      experience:40,
      energy:16,
    }
  },
  {
    level:9,
    requiredClicks:10000000,
    vipCost:50000000,
    rewards:{
      base:500000,
      levelBonus:85,
      experience:45,
      energy:17,
    }
  },
  {
    level:10,
    requiredClicks:100000000,
    vipCost:100000000,
    rewards:{
      base:1000000,
      levelBonus:100,
      experience:50,
      energy:18,
    }
  },
  {
    level:11,
    requiredClicks:1000000000,
    vipCost:1000000000,
    rewards:{
      base:2000000,
      levelBonus:110,
      experience:60,
      energy:20,
    }
  },
]

export const DiscountOnVIP:VipDiscount[] = [
  {
    monthCount:1,
    discount:0,
  },
  {
    monthCount:2,
    discount:3,
  },
  {
    monthCount:3,
    discount:4,
  },
  {
    monthCount:4,
    discount:5,
  },
  {
    monthCount:5,
    discount:6,
  },
  {
    monthCount:6,
    discount:7,
  },
  {
    monthCount:7,
    discount:8,
  },
  {
    monthCount:8,
    discount:9,
  },
  {
    monthCount:9,
    discount:10,
  },
  {
    monthCount:10,
    discount:11,
  },
  {
    monthCount:11,
    discount:12,
  },
  {
    monthCount:12,
    discount:20,
  },
]